# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cefa0e15f9f2ba4b6fe422fcda28adf8e96b5487b98d93e490d987dc346beb3d785cce1ab20e0d388f448c6c95d043e4285cefbf40188c602a8f893606dba34

test:
  secret_key_base: 6aed01b00eade2dc020eb489307e62f6c9d20b3a279b0158c2b24efba67cfd4cb63fa5e7b457f2dc3cbfd0c5d77824e65b975c44569b050620bdb2fdb6dce2e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
